/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cafe.view.main;

import com.cafe.view.sales.SalesPanel;
import javax.swing.*;
/**
 *
 * @author Owner
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super("CafeApp - Sales");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(new SalesPanel());
        setSize(1280, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSidebar = new javax.swing.JPanel();
        pLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pMenu = new javax.swing.JPanel();
        btnSales = new javax.swing.JButton();
        btnTables = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnWarehouse = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        pContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý Cafe");

        pSidebar.setBackground(new java.awt.Color(51, 0, 102));
        pSidebar.setPreferredSize(new java.awt.Dimension(200, 0));
        pSidebar.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Java Coffee");

        javax.swing.GroupLayout pLogoLayout = new javax.swing.GroupLayout(pLogo);
        pLogo.setLayout(pLogoLayout);
        pLogoLayout.setHorizontalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pLogoLayout.setVerticalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogoLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        pSidebar.add(pLogo, java.awt.BorderLayout.PAGE_START);

        pMenu.setLayout(new javax.swing.BoxLayout(pMenu, javax.swing.BoxLayout.Y_AXIS));

        btnSales.setText("Bán hàng");
        pMenu.add(btnSales);

        btnTables.setText("Bàn");
        pMenu.add(btnTables);

        btnProduct.setText("Menu");
        pMenu.add(btnProduct);

        btnWarehouse.setText("Kho");
        pMenu.add(btnWarehouse);

        btnStats.setText("Thống kê");
        pMenu.add(btnStats);

        btnEmployee.setText("Nhân viên");
        pMenu.add(btnEmployee);

        pSidebar.add(pMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(pSidebar, java.awt.BorderLayout.LINE_START);

        pContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        pContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(pContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnStats;
    private javax.swing.JButton btnTables;
    private javax.swing.JButton btnWarehouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pContent;
    private javax.swing.JPanel pLogo;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pSidebar;
    // End of variables declaration//GEN-END:variables
}
