/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.view.warehouse;
import javax.swing.table.DefaultTableModel;
import com.cafe.database.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Le Diu
 */
public class ExportPanel extends javax.swing.JPanel {
    DefaultTableModel model;
    private int stockExport = 0;
    

    /**
     * Creates new form ExportPanel
     */
    public ExportPanel() {
        initComponents();
        initTable();
        loadIngredient();
        loadExport();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbIngredient = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExport = new javax.swing.JTable();
        txtQuantity = new javax.swing.JTextField();
        lblStockExport = new javax.swing.JLabel();
        txtStockExport = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Xuất nguyên liệu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nguyên liệu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng xuất");

        cbIngredient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbIngredient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cà phê bột", "Cà phê hạt", "Đường", "Bột Béo", "Sữa tươi", "Sữa đặc", "Kem béo(Rich)", "Siro", "Mứt/sốt trái cây", " ", " " }));
        cbIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredientActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Danh sách nguyên liệu xuất");

        jButton1.setText("Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblExport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Nguyên liệu", "Số lượng xuất"
            }
        ));
        jScrollPane1.setViewportView(tblExport);

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblStockExport.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblStockExport.setText("Tồn kho hiện tại: ");

        txtStockExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStockExport.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStockExport)
                                .addGap(38, 38, 38)
                                .addComponent(txtStockExport, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jButton1)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbIngredient, txtQuantity});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockExport)
                    .addComponent(txtStockExport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbIngredient, txtQuantity});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int qtyExport;

try {
    qtyExport = Integer.parseInt(txtQuantity.getText());
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Số lượng xuất không hợp lệ!");
    return;
}

if (qtyExport > stockExport) {
    JOptionPane.showMessageDialog(
        this,
        "Không đủ tồn kho! Tồn hiện tại: " + stockExport,
        "Lỗi",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}

exportIngredient(qtyExport);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredientActionPerformed
        // TODO add your handling code here:
        String ingredientName = cbIngredient.getSelectedItem().toString();
        loadStockExport(ingredientName);
    }//GEN-LAST:event_cbIngredientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbIngredient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStockExport;
    private javax.swing.JTable tblExport;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JButton txtStockExport;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        model = new DefaultTableModel();
        model.addColumn("STT");
        model.addColumn("Nguyên liệu");
        model.addColumn("Số lượng xuất");

        tblExport.setModel(model);
    }

    private void loadIngredient() {
        cbIngredient.removeAllItems();

    String sql = "SELECT DISTINCT ingredient_name FROM tbl_import";

    try (Connection conn = DBConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            cbIngredient.addItem(rs.getString("ingredient_name"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    private void loadExport() {
        model.setRowCount(0);
        int stt = 1;

    String sql = """
        SELECT i.ingredient_name,
               e.quantity
        FROM tbl_export e
        JOIN tbl_import i
          ON e.supplier_id = i.supplier_id
    """;

    try (Connection conn = DBConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                stt++,
                rs.getString("ingredient_name"),
                rs.getInt("quantity")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    private void exportIngredient(int qtyExport) {
    String ingredient = cbIngredient.getSelectedItem().toString();

    String sql = """
        INSERT INTO tbl_export (ingredient_name, quantity)
        VALUES (?, ?)
    """;

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, ingredient);
        ps.setInt(2, qtyExport); 
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Xuất thành công!");

        loadExport();                  // reload bảng
        loadStockExport(ingredient);   // cập nhật tồn
        txtQuantity.setText("");       // clear ô nhập

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi xuất!");
        e.printStackTrace();
    }

    }

    private void loadStockExport(String ingredientName) {
String sql = """
        SELECT 
            IFNULL(SUM(quantity), 0)
            -
            IFNULL((
                SELECT SUM(quantity)
                FROM tbl_export
                WHERE ingredient_name = ?
            ), 0) AS stock
        FROM tbl_import
        WHERE ingredient_name = ?
    """;

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, ingredientName);
        ps.setString(2, ingredientName);

        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            stockExport = rs.getInt("stock");
            txtStockExport.setText(String.valueOf(stockExport));
        }

    } catch (Exception e) {
        stockExport = 0;
        txtStockExport.setText("0");
        e.printStackTrace();
    }   
    }
    }
    


