/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.view.warehouse;


import com.cafe.database.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Le Diu
 */
public class ImportPanel extends javax.swing.JPanel {
    int selectedImportId = -1;
    int selectedIngredientId = -1;
    int selectedQuantity = 0;
    DefaultTableModel model;
    /**
     * Creates new form ImportPanel
     */
    public ImportPanel() {
        initComponents();
        
        initTable();
        loadSupplier();
        txtStock.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbIngredient = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImport = new javax.swing.JTable();
        cbSupplier = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhập nguyên liệu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nguyên liệu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhà cung cấp");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá");

        cbIngredient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbIngredient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cà phê bột", "Cà phê hạt", "Đường", "Bột Béo", "Sữa tươi", "Sữa đặc", "Kem béo(Rich)", "Siro", "Mứt/sốt trái cây", " ", " " }));
        cbIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredientActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Danh sách nhập nguyên liệu");

        tblImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Nguyên liệu", "Số lượng", "Đơn giá", "Nhà cung cấp"
            }
        ));
        tblImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblImportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblImport);

        cbSupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblStock.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblStock.setText("Tồn kho hiện tại: ");

        txtStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblStock)
                        .addGap(18, 18, 18)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbIngredient, 0, 195, Short.MAX_VALUE)
                            .addComponent(txtQuantity)
                            .addComponent(txtPrice)
                            .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(27, 27, 27)
                                .addComponent(btnDelete))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSave)))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbIngredient, cbSupplier, txtPrice, txtQuantity});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbIngredient, cbSupplier, txtPrice, txtQuantity});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        addImport();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedImportId == -1) {
        JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Xóa lần nhập này và trừ kho lại?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    String deleteImport = "DELETE FROM tbl_import WHERE import_id = ?";
    String updateStock = """
        UPDATE tbl_ingredient
        SET quantity = quantity - ?
        WHERE ingredient_id = ?
    """;

    try (Connection conn = DBConnection.getConnection()) {
        conn.setAutoCommit(false);

        PreparedStatement ps1 = conn.prepareStatement(deleteImport);
        ps1.setInt(1, selectedImportId);
        ps1.executeUpdate();

        PreparedStatement ps2 = conn.prepareStatement(updateStock);
        ps2.setInt(1, selectedQuantity);
        ps2.setInt(2, selectedIngredientId);
        ps2.executeUpdate();

        conn.commit();

        JOptionPane.showMessageDialog(this, "Xóa thành công");
        loadImport();
        btnResetActionPerformed(null);

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbIngredient.setSelectedIndex(0);
        cbSupplier.setSelectedIndex(0);
        txtQuantity.setText("");
        txtPrice.setText("");
        tblImport.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImportMouseClicked
        // TODO add your handling code here:
        int row = tblImport.getSelectedRow();
    if (row == -1) return;

    selectedImportId = Integer.parseInt(
        model.getValueAt(row, 0).toString()
    );
    selectedIngredientId = Integer.parseInt(
        model.getValueAt(row, 1).toString()
    );
    selectedQuantity = Integer.parseInt(
        model.getValueAt(row, 3).toString()
    );
    }//GEN-LAST:event_tblImportMouseClicked

    private void cbIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredientActionPerformed
        // TODO add your handling code here:
         String ingredientName = cbIngredient.getSelectedItem().toString();

    System.out.println("Đã chọn: " + ingredientName);

    loadTonKho(ingredientName);
    }//GEN-LAST:event_cbIngredientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbIngredient;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStock;
    private javax.swing.JTable tblImport;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        model = new DefaultTableModel();

        model.addColumn("STT");
        model.addColumn("Nguyên liệu");
        model.addColumn("Số lượng");
        model.addColumn("Đơn giá");
        model.addColumn("Nhà cung cấp");

        tblImport.setModel(model);
    }

    private void loadSupplier() {
    cbSupplier.removeAllItems();

    String sql = "SELECT supplier_id, supplier_name FROM tbl_supplier";

    try (Connection conn = DBConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            cbSupplier.addItem(
                rs.getInt("supplier_id") + " - " +
                rs.getString("supplier_name")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }


}

    private void addImport() {
    try {
        String ingredient = cbIngredient.getSelectedItem().toString();
        int quantity = Integer.parseInt(txtQuantity.getText());
        double price = Double.parseDouble(txtPrice.getText());

        String supplierText = cbSupplier.getSelectedItem().toString();
        int supplierId = Integer.parseInt(supplierText.split(" - ")[0]);

        String sql = """
            INSERT INTO tbl_import
            (ingredient_name, quantity, price, supplier_id)
            VALUES (?, ?, ?, ?)
        """;

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, ingredient);
            ps.setInt(2, quantity);
            ps.setDouble(3, price);
            ps.setInt(4, supplierId);
            ps.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Nhập nguyên liệu thành công!");
        loadImport();
        clearForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ!");
    }



    }

    private void loadImport() {
       
    model.setRowCount(0); // xóa dữ liệu cũ
    int stt = 1;

    String sql = """
        SELECT i.ingredient_name,
               i.quantity,
               i.price,
               s.supplier_name
        FROM tbl_import i
        JOIN tbl_supplier s
          ON i.supplier_id = s.supplier_id
    """;

    try (Connection conn = DBConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                stt++,
                rs.getString("ingredient_name"),
                rs.getInt("quantity"),
                rs.getDouble("price"),
                rs.getString("supplier_name")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    

    private void clearForm() {
        txtQuantity.setText("");
        txtPrice.setText("");
        cbIngredient.setSelectedIndex(0);
        cbSupplier.setSelectedIndex(0);
    }
    private int getStockByIngredient(int ingredientId) {
    String sql = """
        SELECT
            COALESCE(SUM(i.quantity), 0)
            - COALESCE((
                SELECT SUM(e.quantity)
                FROM tbl_export e
                WHERE e.ingredient_id = ?
            ), 0) AS stock
        FROM tbl_import i
        WHERE i.ingredient_id = ?
    """;

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, ingredientId);
        ps.setInt(2, ingredientId);

        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt("stock");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return 0;
}
class IngredientItem {
    int id;
    String name;

    @Override
    public String toString() {
        return name;
    }
}

private void loadTonKho(String ingredientName) {
    String sql = "SELECT IFNULL(SUM(quantity), 0) AS ton_kho "
               + "FROM tbl_import WHERE ingredient_name = ?";

    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/cafe_management",
            "root",
            ""
        );

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, ingredientName);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtStock.setText(rs.getInt("ton_kho") + "");
        }

        rs.close();
        ps.close();
        conn.close();

    } catch (Exception e) {
        txtStock.setText("0");
    }
}




    }



