/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.view.warehouse;
import com.cafe.database.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Le Diu
 */
public class StatisticPanel extends javax.swing.JPanel {
DefaultTableModel modelStatistic;
    /**
     * Creates new form StatisticPanel
     */
    public StatisticPanel() {
        initComponents();
        initTable();
        loadStatisticData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatistic = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê nguyên liệu");

        tblStatistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStatistic);

        btnRefresh.setText("Làm mới");

        btnExportExcel.setText("Xuất báo cáo Excel");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm nguyên liệu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnRefresh)
                        .addGap(64, 64, 64)
                        .addComponent(btnExportExcel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnExportExcel))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        loadStatisticData(txtSearch.getText().trim());
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStatistic;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        modelStatistic = new DefaultTableModel();
        modelStatistic.addColumn("STT");
        modelStatistic.addColumn("Tên Nguyên Liệu");
        modelStatistic.addColumn("Tổng Nhập");
        modelStatistic.addColumn("Tổng Xuất");
        modelStatistic.addColumn("Tồn Kho Hiện Tại");
        modelStatistic.addColumn("Trạng Thái");
        tblStatistic.setModel(modelStatistic);
        
        tblStatistic.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            try {
                // Cột số 4 là cột "Tồn Kho" (bắt đầu đếm từ 0, 1, 2, 3, 4)
                Object stockObj = table.getValueAt(row, 4);
                if (stockObj != null) {
                    double stock = Double.parseDouble(stockObj.toString());
                    
                    if (stock <= 5) {
                        c.setForeground(java.awt.Color.RED); // Chữ đỏ nếu sắp hết
                        c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD)); // In đậm cho dễ nhìn
                    } else {
                        c.setForeground(java.awt.Color.BLACK); // Chữ đen bình thường
                        c.setFont(c.getFont().deriveFont(java.awt.Font.PLAIN));
                    }
                }
            } catch (Exception e) {
                c.setForeground(java.awt.Color.BLACK);
            }

            // Giữ màu nền xanh khi người dùng click chọn dòng
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
            } else {
                c.setBackground(table.getBackground());
            }

            return c;
        }
    });
    }
    

    private void loadStatisticData(String keyword) {
        modelStatistic.setRowCount(0);
    // Truy vấn tính toán tồn kho bằng cách lấy (Tổng Nhập - Tổng Xuất)
    String sql = "SELECT n.ingredient_name, " +
                 "SUM(n.quantity) as tong_nhap, " +
                 "IFNULL(x.tong_xuat, 0) as tong_xuat, " +
                 "(SUM(n.quantity) - IFNULL(x.tong_xuat, 0)) as ton_kho " +
                 "FROM tbl_import n " +
                 "LEFT JOIN (SELECT ingredient_name, SUM(quantity) as tong_xuat FROM tbl_export GROUP BY ingredient_name) x " +
                 "ON n.ingredient_name = x.ingredient_name " +
                 "WHERE n.ingredient_name LIKE ? " +
                 "GROUP BY n.ingredient_name";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, "%" + keyword + "%");
        ResultSet rs = ps.executeQuery();
        int stt = 1;
        
        while (rs.next()) {
            double tonKho = rs.getDouble("ton_kho");
            String trangThai = (tonKho <= 5) ? "Sắp hết hàng!" : "Ổn định"; // Cảnh báo nếu dưới 5 đơn vị
            
            modelStatistic.addRow(new Object[]{
                stt++,
                rs.getString("ingredient_name"),
                rs.getDouble("tong_nhap"),
                rs.getDouble("tong_xuat"),
                tonKho,
                trangThai
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
}
